Repository SOPKATHON-iOS-TEAM4/SERVER, pull requests merged in 2024-05, with the labels that each got.

#6 [✅ Chore/#5] 공통응답 & 에러처리 구현
  sopkathon/src/main/java/org/sopt/sopkathon/exception/CustomException.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/GlobalExceptionHandler.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/dto/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/exception/dto/ErrorResponse.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/dto/SuccessResponse.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/ErrorMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
Labels: ✅ Chore

#8 [📂File/#7]: 도메인 설정 및 연관관계 매핑
  sopkathon/src/main/java/org/sopt/sopkathon/domain/Category.java
  sopkathon/src/main/java/org/sopt/sopkathon/domain/MemorizedWord.java
  sopkathon/src/main/java/org/sopt/sopkathon/domain/Word.java
Labels: 🐶 정교

#10 [✨Feat/#9] 카테고리(단어장) 추가 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/CategoryController.java
  sopkathon/src/main/java/org/sopt/sopkathon/controller/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/domain/Category.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/request/CategoryRequest.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/request/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/CategoryRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/service/CategoryService.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/Empty
Labels: ✨ Feat

#12 [✨Feat/#11] 카테고리 리스트 조회 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/CategoryController.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/response/CategoryResponse.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/response/Empty
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/CategoryService.java
Labels: 🐶 정교, ✨ Feat

#15 [✨Feat/#13] 새로운 단어 추가 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/WordController.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/request/WordRequest.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/ErrorMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/WordRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/WordService.java
Labels: 🐶 정교, ✨ Feat

#17 [✨Feat/#14] 단어 리스트 조회 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/MemorizedWordController.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/response/MemorizedWordResponse.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/MemorizedWordRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/MemorizedWordService.java
Labels: ✨ Feat, 🐼 창균

#19 [✨Feat/#16] 단어 리스트 조회 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/CategoryController.java
  sopkathon/src/main/java/org/sopt/sopkathon/controller/WordController.java
  sopkathon/src/main/java/org/sopt/sopkathon/domain/Word.java
  sopkathon/src/main/java/org/sopt/sopkathon/dto/response/WordResponse.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/WordRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/WordService.java
Labels: 🐶 정교, ✨ Feat

#21 [🔨FIX/#20] API 예외사항 수정
  sopkathon/src/main/java/org/sopt/sopkathon/controller/WordController.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/WordRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/WordService.java
Labels: 🐶 정교, 🔨 FIX

#22 [✨Feat/#18] 특정 단어 클릭 시 조회 API 구현
  sopkathon/src/main/java/org/sopt/sopkathon/controller/WordController.java
  sopkathon/src/main/java/org/sopt/sopkathon/domain/Word.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/ErrorMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/exception/enums/SuccessMessage.java
  sopkathon/src/main/java/org/sopt/sopkathon/repository/WordRepository.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/MemorizedWordService.java
  sopkathon/src/main/java/org/sopt/sopkathon/service/WordService.java
Labels: ✨ Feat, 🐼 창균
